### ISSUE TITLE
大佬你网站进入帖子页面一直转圈

### ISSUE THREAD

**Issue by Yakumo-Yukari** [ppap6/PPAP.live#10]
![20200601092548](https://user-images.githubusercontent.com/12076232/83368300-ed789980-a3ea-11ea-8cc6-c2dacbf0de9a.png)

**Comment by jwchan1996** [comment]
emmm，修复了

**Comment by Yakumo-Yukari** [comment]
> emmm，修复了

大佬  请问普通用户是没有头衔的吗？还有就是设置和退出登录 可以加入到点击头像后出现的菜单里会比较合理一些

**Comment by jwchan1996** [comment]
嗯嗯，确实是很多论坛类网站都是点击右上角头像出现菜单设置或者退出登录
这些用户头衔是可以通过有权限的管理员，运营者给用户设置的
头衔是用皇冠图标展示，红色的那个图标是用户角色展示

**Comment by Yakumo-Yukari** [comment]
> 这些用户头衔是可以通过有权限的管理员，运营者给用户设置的
> 头衔是用皇冠图标展示，红色的那个图标是用户角色展示

大佬 你网站没做移动设备的适配吗？现在一般移动端还是使用率比较高
