### ISSUE TITLE
大佬以后会给帖子里加个点赞功能吗？

### ISSUE THREAD

**Issue by Yakumo-Yukari** [ppap6/PPAP.live#12]
加个点赞和点赞用户列表如何？表情像B站那样加个颜文字表情呗

**Comment by jwchan1996** [comment]
😃 帖子点赞是有的，要展示帖子的点赞用户列表，现在数据库的设计处理起来比较难，后面再看吧

😃 颜文字的话，输入法自带了，现阶段还是不要搞太复杂了

😃 感谢建议，Thanks！
