### ISSUE TITLE
大佬请问注册时候生成的昵称+数字是怎么实现的?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [ppap6/PPAP.live#15]
昵称后面的数字是用的什么原理?

**Comment by jwchan1996** [comment]
> 昵称后面的数字是用的什么原理?

(⊙o⊙)…用户量少的阶段可以暂时用时间戳来生成

**Comment by Yakumo-Yukari** [comment]
> > 昵称后面的数字是用的什么原理?
> 
> (⊙o⊙)…用户量少的阶段可以暂时用时间戳来生成

哦哦
