### ISSUE TITLE
建议选择话题使用菜单形式

### ISSUE THREAD

**Issue by Yakumo-Yukari** [ppap6/PPAP.live#17]
![20201017174326](https://user-images.githubusercontent.com/12076232/96334204-8dd11100-10a1-11eb-8f06-c26f8f852063.png)

使用这样的菜单形式选择话题 会比较好 不用全部展示出来 排版会好一些

**Comment by Yakumo-Yukari** [comment]
在社区也发了帖子  但是 看很久站长没管理了 所以就来这提了

**Comment by jwchan1996** [comment]
> ![20201017174326](https://user-images.githubusercontent.com/12076232/96334204-8dd11100-10a1-11eb-8f06-c26f8f852063.png)
> 
> 使用这样的菜单形式选择话题 会比较好 不用全部展示出来 排版会好一些

emmm~ 好的，后面有时间会优化一下~ 谢谢建议~
