### ISSUE TITLE
大佬请问可以使用PPAP来搭建社区吗？

### ISSUE THREAD

**Issue by Yakumo-Yukari** [ppap6/PPAP.live#9]
后端是否也是开源的呢？

**Comment by jwchan1996** [comment]
emmm，可以用来搭建社区，后端也开源的
但是还有功能没写好（比如管理后台），可能还要一两个月

**Comment by Yakumo-Yukari** [comment]
> emmm，可以用来搭建社区，后端也开源的
> 但是还有功能没写好（比如管理后台），可能还要一两个月

哦 好的  好像go版本的后端没怎么更新呢
